### PR TITLE
This adds support for the use of nonces

### PR DESCRIPTION
**Pull request by splitbrain**
The change will ininitialize a random nonce on every call and add it to the environment from where it will be picked up by the changes introduced in https://github.com/dokuwiki/dokuwiki/pull/4220

Users may use that nonce in their CSP directives by using the placeholder NONCE. Eg the script-src dirctive might use 'nonce-NONCE' resulting in a header script-src: 'nonce-1cccd1f6fb2939edd9fa9372b67017b3'; or similar.

### CODE REVIEW

**Review by dregad — CHANGES_REQUESTED** [review]
Thank you @splitbrain 

Can you please update the plugin's doc page https://www.dokuwiki.org/plugin:cspheader with usage instructions. An example, maybe a screenshot to illustrate would be nice.

Question, would there be any backwards-compatibility issues for someone using a new version of this plugin including your change, with a Dokuwiki release that does not include the changes in dokuwiki/dokuwiki#4220 ?

**Comment by splitbrain** [comment]
I can update the docs when this is merged. I gave an example in the description. This changes does not affect users on older releases. It will not even affect users running current master unless they configure their settings to make use of the nonce.

**Comment by dregad** [comment]
OK great ! Thanks for the feedback and clarification.

I'll try to merge this and release new version over the week-end.

**Comment by dregad** [comment]
New release is published. I let you update the docs. Thanks !

**Pull request merged**
